import os

top = "."
out = "build"
install_suffix = os.environ.get("WAF_DEFAULT_VARIANT") or os.environ.get("WAF_SUFFIX", "mpi")
default_prefix = "../install/%s" % install_suffix


def options(self):
    self.recurse("src/bibfor")
    self.recurse("src/bibc")


def configure(self):
    self.add_os_flags("FCFLAGS")

    self.recurse("src/bibfor")
    self.recurse("src/bibc")
    # At the moment only needed if not using latest WAF master branch
    # self.load("ifort", tooldir="src/waftools")


def build(self):
    self.load("msvc_utils", tooldir="src/waftools")
    self.recurse("src/bibfor")
    self.recurse("src/bibc")
