import os
from waflib import Build, Configure, Logs, Utils
from waflib.Tools.c_config import DEFKEYS
from waflib.Tools.fc import fc

top = "."
out = "build"
install_suffix = os.environ.get("WAF_DEFAULT_VARIANT") or os.environ.get("WAF_SUFFIX", "mpi")
default_prefix = "../install/%s" % install_suffix


def options(self):
    self.recurse("src/bibfor")
    self.recurse("src/bibc")


def configure(self):
    self.load("ifort", tooldir="src/waftools")
    self.recurse("src/bibfor")
    self.recurse("src/bibc")


def build(self):
    self.recurse("src/bibfor")
    self.recurse("src/bibc")
