import pathlib

from waflib import Build


def options(opt):
    opt.load('compiler_c')


def configure(conf):
    conf.load('compiler_c')


def build(ctx: Build.InstallContext):
    ctx(
        features="c cshlib",
        name="asterbibclib",
        source='bibclib.c',
        target='bibclib',
        includes=[".", 'include'],
        use='asterbibfor',
    )

    library_prefix_dir = pathlib.Path(ctx.env.PREFIX)
    prefix_dir = library_prefix_dir.parent
    py_include = prefix_dir / 'include'
    pybind11_incl = prefix_dir / 'include' / 'pybind11_global'
    ctx(
        features="c cshlib",
        name="asterpylib",
        source='python_entry.c',
        target='bibpylib',
        includes=[".", 'include', pybind11_incl.as_posix(), py_include.as_posix()],
    )

    ctx(
        features="c cprogram",
        name="asterbibc",
        source='main.c',
        target='bibcmain',
        use='asterbibclib',
    )
