from waflib import Build


def options(opt):
    opt.load('compiler_c')


def configure(conf):
    conf.load('compiler_c')


def build(ctx: Build.InstallContext):
    ctx(
        features="c cprogram",
        name="asterbibc",
        source='main.c',
        target='bibcmain',
        use='bibfor',
    )
