from waflib import Build, Configure


def options(opt):
    opt.load('compiler_fc')


def configure(conf):
    conf.load('compiler_fc')


@Configure.conf
def check_fortran_compiler_flags(self):
    self.check_fortran_compiler_options(["/nologo"])
    self.start_msg("Fortran compiler flags")
    self.end_msg(self.env["FCFLAGS"])


def build(ctx: Build.InstallContext):
    get_srcs = ctx.path.get_src().ant_glob

    ctx(
        features="fc fcshlib",
        name="asterbibfor",
        source=get_srcs("**/*.f90"),
        target='bibfor',
        includes=["include"],
    )
