def options(opt):
    opt.load('compiler_fc')


def configure(conf):
    conf.load('compiler_fc')


def build(bld):
    bld(
        features="fc fcshlib",
        name="asterbibfor",
        source='func.f90',
        target='bibfor'
    )
